### PR TITLE
500 error when running Syncto locally with WiFi disabled.

### PR DESCRIPTION
**Pull request by Natim**
Simple to reproduce, at least on my machine ;)
- Run syncto on localhost.
- See everything work fine.
- Disconnect from wifi.
- Next request to syncto will yield a 500 Internal Server Error.

Maybe something like '503 Service Unavailable' would be more appropriate (I guess we want 500 to never ever occur?).

### CODE REVIEW

**Comment by Natim** [comment]
> I guess we want 500 to never ever occur?

True, let me try this.

**Comment by Natim** [comment]
The error triggering a 500 is a Connection Error:

```
  File "requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'));
```

**Comment by leplatrem** [comment]
LGTM r+

**Comment by michielbdejong** [comment]
Thanks!!

**Pull request merged**
