### PR TITLE
Enable CORS and bump version so it works with kinto.js

### PR DESCRIPTION
**Pull request by ferjm**

### CODE REVIEW

**Comment by Natim** [comment]
Thank you for this, I will add some tests and see if we cannot use the Cornice CORS feature to handle this.

**Comment by Natim** [comment]
I wrote a test for CORS on the GET and it seems to work. Will add more tests.

**Comment by Natim** [comment]
See https://github.com/mozilla-services/syncto/blob/1be8cf633ff29f6e0dd16b3c8c75bd381d6656b0/syncto/tests/test_functional.py#L64-L81

**Comment by almet** [comment]
Yes, Cornice [normally handles this in a dynamic way](http://cornice.readthedocs.org/en/latest/api.html) (so there is no need to force the headers like this)

**Comment by almet** [comment]
@natim does this mean we can close this pull request (as CORS is already handled). @ferjm do you have cases where the CORS headers aren't sent where they should?

**Comment by Natim** [comment]
Yes I will add more tests about Cors in Syncto but I think this is not mandatory.

**Pull request closed without merging**
